### ISSUE TITLE
Remove private rsa key from lmctl for netconf driver

### ISSUE THREAD

**Issue by rkumar8j** [IBM/lmctl#143]
brent provides rsa key feature to driver so removing private rsa key from lmctl for netconf driver as it is not required to keep inside driver's implementation.

**Comment by dvaccarosenna** [comment]
@rkumar8j please don't refer to internal issues here, it's not useful for those without internal access. 

Also, I can't see the reason for needing to remove the rsa key? Isn't it just an example key used when generating a new project?

**Comment by rkumar8j** [comment]
@dvaccarosenna : Initially we had kept the keys as part of resource package inside the keys folder for netconf but after using Brent infrastructure keys, we don't require these keys to be part of resource package. So we need to remove these references from lmctl for netconf driver.
