### ISSUE TITLE
Can we override the properties value through command line while running behaviour test. 

### ISSUE THREAD

**Issue by GeitRavi** [IBM/lmctl#149]
Can we override the properties value through command line while running behaviour test (lmctl project test )

There are few parameter/properties are defined in Configuration file under Behaviour tests. Is there any way we can override the value present in config.json while executing lmctl project test command ? 

behavior Dir structure
 - Configuration/config.json
 - Runtime
 - Test 

----
Config.json 

{
  "name": "Example",
  "projectId": "$lmctl:/Example",
  "description": "test example",
  "descriptorName": "$lmctl:/example",
  "properties": {
    "deploymentLocation": "example",
    "**host**": "",
    "user": "",
    "ssh_pass": ""
  }
}

**Comment by dvaccarosenna** [comment]
Hi @GeitRavi, no there isn't. The Behaviour Testing API does not support this either, for a single execution. You have to update the Configuration first, then run the Scenario.
