### ISSUE TITLE
Add commands in LMCTL to retry, rollback and cancel intent process.

### ISSUE THREAD

**Issue by maheshlokhande1** [IBM/lmctl#163]
An intent process invoked by lmctl can subsequently be canceled, retried, or rolled back via the CP4NA GUI or its APIs. To support the rollback case, lmctl supports the processState, of the intent processes invoked by lmctl, being Rolling Back (as a transient state) or Rolled Back (as a terminal state).

cancel, retry or rollback can also be invoked using the following lmctl commands respectively, where the ID value is the processId value of the intent process.

`lmctl rollback process [OPTIONS] ID`
`lmctl rollback process [OPTIONS] ID`
`lmctl rollback process [OPTIONS] ID`

**Comment by dvaccarosenna** [comment]
Fixed by #164
