### ISSUE TITLE
lmctl project test executing all the behaviors

### ISSUE THREAD

**Issue by amanrubalibm** [IBM/lmctl#69]
lmctl project test executing all the behaviors even when a particular one is specified in the command using '--tests'

Steps to reproduce the behaviour:

use lmctl to execute a specific test :
the ones we tried :  " lmctl project test <env> --armname brent --tests <testname> "
                                 " lmctl project test  --armname brent --tests <testname>  <env>"
                                 " lmctl project test <env>  --tests <testname>"

It executes all the tests from the behavior tests folder in the assembly.

using ALM2.2 and LMCTL2.6.0

**Comment by dvaccarosenna** [comment]
Can confirm this is a bug as the value of the `tests` option is not being passed through to the `exec_test` in https://github.com/IBM/lmctl/blob/master/lmctl/cli/commands/project.py#L121

**Comment by dvaccarosenna** [comment]
Closed by #70

**Comment by dvaccarosenna** [comment]
This fix will appear in the upcoming v2.6.1 release (should be today)
